### ISSUE TITLE
Request for Fixed Version Release Scheme

### ISSUE THREAD

**Issue by alexandergraul** [openSUSE/opensuse-theme-chameleon#5]
Currently the theme gets updated and other projects that want to implement it use an arbitrary commit.
I'd like to request some version scheme for releases so other implementations have an easier time using the theme.

[GitHub Docs](https://help.github.com/articles/creating-releases/) cover the bases of how to create releases, I am also willing to help out with setting this up, but I don't know enough about the development process to be able to decide on releases or a naming/versioning scheme.

**Comment by guoyunhe** [comment]
I agree that a good version scheme and changelog make sense for other projects. The theme itself has been used for software and wiki for some time and it should be stable for normal usage. So my plan is to:

1. Release version 1.0.0 with current code.
2. Follow semantic versioning.
3. Keep a changlog.
4. Publish packages to Ruby Gem, PHP Composer, NPM.
5. Package RPM in OBS.

**Comment by alexandergraul** [comment]
Cool, if you need help with git or something let me know :+1:

**Comment by guoyunhe** [comment]
I updated changelog and readme, and released 1.0.0. They can make the Ruby Gem configuration here instead of making a new repository.

**Comment by guoyunhe** [comment]
This issue has been solved.
